version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=autograb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "15432:5432"
  redis:
    image: 'redis:latest'
    ports:
      - "16379:6379"

  backend:
    restart: on-failure:10
    image: motionrus/autograb-backend:latest
    build: backend
    command: >
      sh -c "
        python manage.py collectstatic --noinput &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
  ui:
    image: ghcr.io/motionrus/autograb-ui:latest
    ports:
      - "4848:80"

  chrome:
    image: selenium/node-chrome:4.3.0-20220726
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6900:5900"
      - "7900:7900"

  edge:
    image: selenium/node-edge:4.3.0-20220726
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6901:5900"

  firefox:
    image: selenium/node-firefox:4.3.0-20220726
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6902:5900"

  selenium-hub:
    image: selenium/hub:4.3.0-20220726
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  worker:
    restart: on-failure:10
    image: motionrus/autograb-backend:latest
    build: backend
    command: >
      sh -c "python manage.py rqworker high default"
    volumes:
      - ./backend:/code
    depends_on:
      - db
      - redis
    environment:
      - DOCKER_WORKER=1
    env_file:
      - .env

volumes:
  db_volume:
    external: true
