version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=autograb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  backend:
    build: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_URL=postgres://postgres:postgres@db/autograb
    env_file:
      .env
    depends_on:
      - db
  ui:
    build: ui
    ports:
      - "4848:80"

volumes:
  db_volume:
    external: true