# Generated by Django 4.0.5 on 2022-06-26 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0002_ad_status_ad_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ad',
            name='rating',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
