# Generated by Django 4.0.5 on 2022-06-26 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0003_alter_ad_date_alter_ad_description_alter_ad_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
