# Generated by Django 4.0.5 on 2022-07-09 09:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0006_parser'),
    ]

    operations = [
        migrations.AddField(
            model_name='parser',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parser',
            name='status',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
