# Generated by Django 4.0.5 on 2022-07-18 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0007_parser_percentage_parser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='need_updates',
            field=models.BooleanField(default=False),
        ),
    ]
